app/insta/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),  # http://localhost:8000/plagigram/
    path('addpost/', views.add_post, name='addpost'),  # http://localhost:8000/plagigram/addpost/
    path('post/<int:post_id>/', views.post_comments, name='comments'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('posts_by_tag/<str:tag>/', views.posts_by_tag, name='posts_by_tag'),
]

app/plagigram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from plagigram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plagigram/', include('insta.urls')),
    path('plagigram/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('subscribe/<str:username>/', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:username>/', views.unsubscribe, name='unsubscribe'),

]

app/insta/models.py
from cloudinary.uploader import upload
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField
from cloudinary.uploader import upload_large

from users.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags')

    objects = models.Manager()


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)

    objects = models.Manager()

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('posts_by_tag', args=[str(self.tag)])


class UploadImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, null=True, blank=True)
    image = CloudinaryField('images')


class UploadVideo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, null=True, blank=True)
    video_file = CloudinaryField(resource_type='video')


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(blank=True)

    objects = models.Manager()


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    objects = models.Manager()

app/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


from .managers import CustomUserManager


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users/avatars/', blank=True, null=True)
    biography = models.TextField(blank=True, verbose_name="Biography")
    followers = models.ManyToManyField('self', symmetrical=True)
    email = models.EmailField(_('email'), unique=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()


class Subscription(models.Model):
    follower = models.ForeignKey(User, related_name='subscribers', on_delete=models.CASCADE)
    followee = models.ForeignKey(User, related_name='subscriptions', on_delete=models.CASCADE)

    objects = models.Manager()

app/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    email = forms.CharField(label='E-mail',
                            widget=forms.TextInput(attrs={'class': 'from-input'}))
    password = forms.CharField(label='Password',
                               widget=forms.TextInput(attrs={'class': 'from-input'}))

    class Meta:
        model = get_user_model()
        fields = ['email', 'password']


class RegisterUserForm(UserCreationForm):
    email = forms.CharField(label="email", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Reenter the password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': "Имя",
            'last_name': "Фамилия",
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Such an E-mail already exists!")
        return email


class ProfileUserForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ['avatar', 'biography', ]

app/users/views.py
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm
from users.models import User, Subscription


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {"title": "Авторизация"}

    def form_valid(self, form):
        # Используйте кастомный бэкенд для аутентификации по email
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(request=self.request, email=email, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            # Обработайте случай, когда аутентификация не удалась
            return self.form_invalid(form)


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': "Профиль пользователя",
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def user_profile(request, username):
    profile_user = get_object_or_404(get_user_model(), username=username)
    is_owner = request.user == profile_user

    is_following = Subscription.objects.filter(follower=request.user, followee=profile_user).exists()

    num_followers = profile_user.subscribers.count()
    num_following = profile_user.subscriptions.count()

    context = {
        'profile_user': profile_user,
        'is_owner': is_owner,
        'is_following': is_following,
        'num_followers': num_followers,
        'num_following': num_following,
        'title': "Профиль пользователя",
    }

    return render(request, 'users/user_profile.html', context)


@login_required
def subscribe(request, username):
    user_to_subscribe = get_object_or_404(User, username=username)

    # Проверяем, существует ли уже подписка
    if not Subscription.objects.filter(follower=request.user, followee=user_to_subscribe).exists():
        Subscription.objects.create(follower=request.user, followee=user_to_subscribe)

    return redirect('users:user_profile', username=username)


@login_required
def unsubscribe(request, username):
    user_to_unsubscribe = get_object_or_404(User, username=username)

    # Проверяем, существует ли подписка перед удалением
    subscription = Subscription.objects.filter(follower=request.user, followee=user_to_unsubscribe).first()
    if subscription:
        subscription.delete()

    return redirect('users:user_profile', username=username)

app/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Авторизация</h1>

    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        <div class="form-group">
            {% for f in form %}
            <label for="{{ f.id_for_label }}" class="col-sm-2 control-label">{{ f.label }}</label>
            <div class="col-sm-10">
                {{ f }}
                <div class="form-error">{{ f.errors }}</div>
            </div>
            {% endfor %}
        </div>
        <div class="form-group mt-3">
            <div class="col-sm-offset-2 col-sm-10">
                <p><button type="submit" class="btn btn-primary btn-lg">Войти</button></p>
            </div>
        </div>
    </form>

    <p>У вас ещё нет аккаунта? <a href="{% url 'users:register' %}">Зарегистрироваться</a></p>

    <div class="row">
        <div class="col-md-8 mx-auto social-container my-2 order-md-1">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-primary mb-2" style="text-decoration: none; color: #ffffff;">
                Login With Google
            </a>
        </div>
    </div>


{% endblock %}

app/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="profile">{{user.username}} | <a href="{% url 'users:logout' %}">Выйти</a></h1>


<form class="profile" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    <div class="flex-container">
        <div class="avatar-container">
            {% if user.avatar %}
                <img class="avatar" src="{{ user.avatar.url }}">
            {% else %}
                <img class="avatar" src="{% static 'users/images/default.png' %}">
            {% endif %}
        </div>

        <div class="profile-followers">
            <p>{{ user.subscriptions.count }} подписчиков</p>
        </div>

        <div class="profile-following">
            <p>{{ user.subscribers.count }} подписок</p>
        </div>
    </div>

    <div class="biography-container">
        {% for f in form %}
            {% if f.name == 'biography' %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
            {% endif %}
        {% endfor %}
    </div>

    <p><label class="form-label" for="{{ form.avatar.id_for_label }}"></label>{{ form.avatar }}</p>
    <div class="form-error">{{ form.avatar.errors }}</div>

    <p><button type="submit">Сохранить</button></p>
</form>

<h2 class="center-block-profile">You posts</h2>
<div class="you-posts-profile">
    {% for post in user.post_set.all %}
        {% with img=post.uploadimage_set.first %}
            {% if img %}
                <a href="{% url 'comments' post_id=post.id %}">
                    {% load cloudinary %}
                    {% cloudinary img.image quality='auto' width=200 height=200 crop='pad' background='gen_fill:ignore-foreground_true' %}
                </a>
            {% endif %}
        {% endwith %}

        {% with video=post.uploadvideo_set.first %}
            {% if video %}
                <a href="{% url 'comments' post_id=post.id %}">
                    {% load cloudinary %}
                    <video width="200" height="200" controls>
                        <source src="{{ video.video_file }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </a>
            {% endif %}
        {% endwith %}
    {% endfor %}
</div>

{% endblock %}

app/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form class="form-horizontal" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    <div class="form-group">
        {% for f in form %}
        <label class="col-sm-2 control-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
        <div class="col-sm-10">
            {{ f }}
            <div class="form-error">{{ f.errors }}</div>
        </div>
        {% endfor %}
    </div>
    <div class="form-group mt-3">
        <div class="col-sm-offset-2 col-sm-10">
            <p><button type="submit" class="btn btn-primary btn-lg">Регистрация</button></p>
        </div>
    </div>
</form>

{% endblock %}

app/users/templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="profile">{{ profile_user.username }}
    {% if not is_owner %}
        <div class="subscribe-button">
            {% if is_following %}
                <form method="post" action="{% url 'users:unsubscribe' profile_user.username %}">
                    {% csrf_token %}
                        <button type="submit">Отписаться</button>
                </form>
                    {% else %}
                <form method="post" action="{% url 'users:subscribe' profile_user.username %}">
                    {% csrf_token %}
                        <button type="submit">Подписаться</button>
                </form>
                    {% endif %}
        </div>
    {% endif %}
</h1>

<div class="profile">
    <div class="flex-container">
        <div class="avatar-container">
            {% if profile_user.avatar %}
                <img class="avatar" src="{{ profile_user.avatar.url }}">
            {% else %}
                <img class="avatar" src="{% static 'users/images/default.png' %}">
            {% endif %}
        </div>

        {% if is_owner %}
        <div class="profile-followers">
            <p>{{ user.subscriptions.count }} подписчиков</p>
        </div>

        <div class="profile-following">
            <p>{{ user.subscribers.count }} подписок</p>
        </div>
        {% else %}
        <div class="profile-followers">
            <p>{{ num_following }} подписчиков</p>
        </div>

        <div class="profile-following">
            <p>{{ num_followers }} подписок</p>
        </div>
        {% endif %}
    </div>

    <div class="biography-container">
        <p class="author-title">Biography:</p>
        <p class="author-bio">{{ profile_user.biography }}</p>
    </div>
</div>
{% if is_owner %}
    <p class="user-profile" ><a href="{% url 'users:profile' %}">Редактировать</a></p>
{% endif %}

<h2 class="center-block-profile">Posts by {{ profile_user.username }}</h2>
<div class="you-posts-profile">
    {% for post in profile_user.post_set.all %}
        {% with img=post.uploadimage_set.first %}
            {% if img %}
                <a href="{% url 'comments' post_id=post.id %}">
                    {% load cloudinary %}
                    {% cloudinary img.image quality='auto' width=200 height=200 crop='pad' background='gen_fill:ignore-foreground_true' %}
                </a>
            {% endif %}
        {% endwith %}

        {% with video=post.uploadvideo_set.first %}
            {% if video %}
                <a href="{% url 'comments' post_id=post.id %}">
                    {% load cloudinary %}
                    <video width="200" height="200" controls>
                        <source src="{{ video.video_file }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </a>
            {% endif %}
        {% endwith %}
    {% endfor %}
</div>

{% endblock %}