app/insta/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),  # http://localhost:8000/plagigram/
    path('addpost/', views.add_post, name='addpost'),  # http://localhost:8000/plagigram/addpost/
    path('post/<int:post_id>/', views.post_comments, name='comments'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('posts_by_tag/<str:tag>/', views.posts_by_tag, name='posts_by_tag'),
]

app/plagigram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from plagigram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plagigram/', include('insta.urls')),
    path('plagigram/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('subscribe/<str:username>/', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:username>/', views.unsubscribe, name='unsubscribe'),

]

app/insta/models.py
from cloudinary.uploader import upload
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField
from cloudinary.uploader import upload_large

from users.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField(blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags')

    objects = models.Manager()


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)

    objects = models.Manager()

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('posts_by_tag', args=[str(self.tag)])


class UploadImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, null=True, blank=True)
    image = CloudinaryField('images')


class UploadVideo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, null=True, blank=True)
    video_file = CloudinaryField(resource_type='video')


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(blank=True)

    objects = models.Manager()


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    objects = models.Manager()

app/insta/forms.py
from django import forms
from django.forms.models import inlineformset_factory, modelformset_factory
from .models import Post, UploadImage, Comment, TagPost, UploadVideo
from cloudinary.forms import CloudinaryFileField


class AddPostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=TagPost.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Post
        fields = ['title', 'text', 'tags']


class UploadImageForm(forms.ModelForm):
    image = CloudinaryFileField()

    class Meta:
        model = UploadImage
        fields = '__all__'


class UploadVideoForm(forms.ModelForm):
    video_file = CloudinaryFileField(
        options={
            'folder': 'uploads',
            'resource_type': 'video',
            'allowed_formats': ['mp4', 'mov', 'avi'],
        }
    )

    class Meta:
        model = UploadVideo
        fields = '__all__'


PostUploadImageFormSet = inlineformset_factory(Post, UploadImage, form=UploadImageForm,
                                               fields=('image',), extra=1, can_delete=True, )

PostUploadVideoFormSet = inlineformset_factory(Post, UploadVideo, form=UploadVideoForm,
                                               fields=('video_file',), extra=1, can_delete=True, )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

app/insta/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from insta.forms import AddPostForm, CommentForm, PostUploadImageFormSet, PostUploadVideoFormSet
from insta.models import Post, Comment, Like, TagPost
from cloudinary.uploader import upload

import cloudinary
import cloudinary.uploader
import cloudinary.api


@login_required
def index(request):
    posts = Post.objects.all()
    data = {
        'title': 'Plagigram',
        'posts': posts,
    }
    return render(request, 'insta/index.html', context=data)


@login_required
def add_post(request):
    if request.method == 'POST':
        post_form = AddPostForm(request.POST)
        image_formset = PostUploadImageFormSet(request.POST, request.FILES, prefix='image')
        video_formset = PostUploadVideoFormSet(request.POST, request.FILES, prefix='video_file')

        if post_form.is_valid() and image_formset.is_valid() and video_formset.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()

            post.tags.set(post_form.cleaned_data['tags'])

            image_formset.instance = post
            image_formset.save()

            video_formset.instance = post
            video_formset.save()

            for video_file_instance in post.uploadvideo_set.all():
                video_file_url = upload_to_cloudinary(video_file_instance.video_file.url)
                video_file_instance.video_file = video_file_url
                video_file_instance.save()

            return redirect('home')

    else:
        post_form = AddPostForm()
        image_formset = PostUploadImageFormSet(prefix='image')
        video_formset = PostUploadVideoFormSet(prefix='video_file')

    tag_list = TagPost.objects.all()

    data = {
        'title': 'Add post',
        'form': post_form,
        'video_formset': video_formset,
        'image_formset': image_formset,
        'tag_list': tag_list,
    }
    return render(request, 'insta/addpost.html', data)


def upload_to_cloudinary(file, is_file_path=False):
    if is_file_path:
        with open(file, 'rb') as video_file:
            res = cloudinary.uploader.upload_large(video_file, resource_type="video")
    else:
        res = cloudinary.uploader.upload_large(file, resource_type="video")

    return res['secure_url']


@login_required
def post_comments(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm()

    return render(request, 'insta/comments.html', {'post': post,
                                                   'comments': comments, 'form': form, 'title': 'Post'})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data['text']
            if comment_text.strip():
                comment = form.save(commit=False)
                comment.post = post
                comment.user = request.user
                comment.save()

    return redirect('comments', post_id=post_id)


@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user

    try:
        existing_like = Like.objects.get(user=user, post=post)
        existing_like.delete()
        liked = False
    except ObjectDoesNotExist:
        Like.objects.create(user=user, post=post)
        liked = True
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

    likes_count = post.like_set.count()

    return JsonResponse({'liked': liked, 'likes_count': likes_count})


def posts_by_tag(request, tag):
    tag = get_object_or_404(TagPost, tag=tag)
    posts = Post.objects.filter(tags=tag)

    return render(request, 'insta/index.html', {'tag': tag, 'posts': posts, 'title': f"Posts by {tag}"})

app/insta/templates/insta/addpost.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        {% if f.name != 'tags' %}
            <div class="form-group">
                <label class="col-sm-2 control-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                <div class="col-sm-10">
                    {{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    {{ image_formset.management_form }}
    {% for form in image_formset %}
        <div class="form-group">
            <label class="col-sm-2 control-label" for="{{ form.image.id_for_label }}">{{ form.image.label_tag }}</label>
            <div class="col-sm-10">
                {{ form.image }}
            </div>
        </div>
    {% endfor %}

    {{ video_formset.management_form }}
    {% for form in video_formset %}
        <div class="form-group">
            <label class="col-sm-2 control-label" for="{{ form.video_file.id_for_label }}">{{ form.video_file.label_tag }}</label>
            <div class="col-sm-10">
                {{ form.video_file }}
            </div>
        </div>
    {% endfor %}

    <div class="form-group">
        <label class="col-sm-2 control-label" for="{{ form.tags.id_for_label }}">{{ form.tags.label }}:</label>
        <div class="col-sm-10">
            {{ form.tags }}
            <datalist id="tag_list">
                {% for tag in tag_list %}
                    <option value="{{ tag.tag }}">
                {% endfor %}
            </datalist>
        </div>
    </div>
    <div class="form-group mt-3">
        <div class="col-sm-offset-2 col-sm-10">
            <p><button type="submit" class="btn btn-primary btn-lg">Send</button></p>
        </div>
    </div>
</form>
{% endblock %}

app/insta/templates/insta/comments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="post-details">
    <div class="post-image-comment">
        {% for media_file in post.uploadimage_set.all %}
            {% load cloudinary %}
            {% cloudinary media_file.image quality='auto' width=930 height=930 crop='pad' background='gen_fill:ignore-foreground_true' %}
        {% endfor %}

        {% for media_file in post.uploadvideo_set.all %}
        {% load cloudinary %}
            <video width="800" height="720" controls>
                <source src="{{ media_file.video_file }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        {% endfor %}
    </div>
    <div class="comments-section">
        <h2>Comments on this post</h2>
        <div class="comments-container">
            <div class="comment-list">
                {% for comment in comments %}
                    <div class="comment-container">
                        <div class="avatar-container">
                            {% if comment.user.avatar %}
                                <img class="comment-avatar" src="{{ comment.user.avatar.url }}">
                            {% else %}
                                <img class="avatar" src="{% static 'users/images/default.png' %}">
                            {% endif %}
                        </div>
                        <div class="comment-content">
                            <a href="{% url 'users:user_profile' username=comment.user.username %}"><strong>{{ comment.user.username }}</strong></a>: {{ comment.text | linebreaksbr }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <form method="post" action="{% url 'add_comment' post_id=post.id %}">
            {% csrf_token %}
            <div>
                <label for="{{ form.text.id_for_label }}">Прокомментировать:</label>
                {{ form.text }}
            </div>
            <div>
                <button type="submit" class="comment-button">Send</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/insta/templates/insta/index.html
{% extends 'base.html' %}

{% block content %}
<script>
$(document).ready(function(){
    $(".like-post").on("click", function(e){
        e.preventDefault();
        var post_id = $(this).data("post-id");

        $.ajax({
            type: "POST",
            url: "{% url 'like_post' post_id=0 %}".replace('0', post_id),
            data: {
                'post_id': post_id,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(data){
                $(".likes-count-" + post_id).text(data.likes_count);
            },
            error: function(data){
                console.log("Error:", data);
            }
        });
    });
});
</script>

<ul class="list-articles">
    {% for p in posts %}
        <li>
            <a href="{% url 'users:user_profile' username=p.user.username %}">
                <h2>{{ p.user }}</h2>
            </a>

            {% for media_file in p.uploadimage_set.all %}
                {% load cloudinary %}
                    {% cloudinary media_file.image quality='auto' width=460 height=460 crop='pad' background='gen_fill:ignore-foreground_true' %}
            {% endfor %}

            {% for media_file in p.uploadvideo_set.all %}
                {% load cloudinary %}
                <video width="460" height="380" controls>
                    <source src="{{ media_file.video_file }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            {% endfor %}



            <div class="post-details">
                <a href="{% url 'like_post' post_id=p.id %}" class="like-post" data-post-id="{{ p.id }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.920 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                    </svg>
                </a>
                <a href="{% url 'comments' post_id=p.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                    </svg>
                </a>
            </div>
            <p>Likes: <span class="likes-count-{{ p.id }}">{{ p.like_set.count }}</span> | Comments: {{ p.comment_set.count }}</p>
            <div class="post-tags">
                    Tags:
                    {% for tag in p.tags.all %}
                        <a href="{{ tag.get_absolute_url }}" class="tag">{{ tag.tag }}</a>
                    {% endfor %}
            </div>

            <h3>{{ p.title }}</h3>

            {% autoescape off %}
                {{ p.text|linebreaks }}
            {% endautoescape %}
        </li>
    {% endfor %}
</ul>
{% endblock %}