app/insta/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),  # http://localhost:8000/plagigram/
    path('addpost/', views.add_post, name='addpost'),  # http://localhost:8000/plagigram/addpost/
    path('post/<int:post_id>/', views.post_comments, name='comments'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('posts_by_tag/<str:tag>/', views.posts_by_tag, name='posts_by_tag'),
]

app/plagigram/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from plagigram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plagigram/', include('insta.urls')),
    path('plagigram/', include('users.urls', namespace='users')),
    path('social-auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('subscribe/<str:username>/', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:username>/', views.unsubscribe, name='unsubscribe'),

]

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
	<link rel="shortcut icon" href="{% static 'insta/images/main.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'insta/js/dist/bundle.js' %}"></script>
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>

<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li><a href="{% url 'home' %}">Главная</a></li>
		<li><a href="{% url 'users:profile' %}">Профиль</a></li>
		<li><a href="{% url 'addpost' %}">Создать</a></li>
	</ul>
</td>
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

	<div class="content-text">
{% block content %}
{% endblock %}
	</div>

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy; 2023 Partial or complete copying of information from this site for distribution on other resources, including paper, is strictly prohibited.</p>
	</div>
</td></tr></table>
</body>
</html>